import type { ModelRow, StationPayload } from "./types";

/** Test helpers only (not imported by the app). */

export function ensembleRow(partial: Partial<ModelRow> & Pick<ModelRow, "id">): ModelRow {
  return {
    label: partial.id,
    role: "blend",
    rawMaxC: 22.1,
    rawMinC: 11.0,
    correctionC: -0.42,
    correctionN: 180,
    correctedMaxC: 22.52,
    status: "selected",
    weight: 0.5,
    deltaC: 0,
    available: true,
    ...partial,
  };
}

/** EDDM-like calibrated-ensemble station payload. */
export function ensemblePayload(overrides: Partial<StationPayload> = {}): StationPayload {
  return {
    station: {
      icao: "EDDM",
      city: "Munich",
      name: "Munich",
      region: "europe",
      lat: 48.35,
      lon: 11.78,
      timezone: "Europe/Berlin",
      defaultUnit: "C",
      primary: "icon_d2",
      primaryModels: ["icon_d2"],
      backups: [],
      notes: [],
      warnings: [],
      ensemble: true,
    },
    day: "today",
    marketDate: "2026-09-16",
    localNow: "2026-09-16T11:00:00",
    forecast: {
      models: [
        ensembleRow({
          id: "icon_d2",
          label: "ICON-D2",
          rawMaxC: 25.3,
          correctionC: -0.6,
          correctedMaxC: 25.9,
          run: {
            initAt: "2026-09-16T06:00:00.000Z",
            initZ: "06Z",
            availableAt: "2026-09-16T07:26:00.000Z",
            dataset: "dwd_icon_d2",
            nest: null,
          },
        }),
        ensembleRow({
          id: "meteofrance_arome_france_hd",
          label: "AROME France HD",
          rawMaxC: 25.1,
          correctionC: 0.2,
          correctedMaxC: 24.9,
        }),
        ensembleRow({
          id: "icon_global",
          label: "ICON global",
          role: "ensemble",
          rawMaxC: 24.0,
          correctionC: -1.0,
          correctedMaxC: 25.0,
          status: "redundant",
          weight: null,
        }),
      ],
      requestedModels: ["icon_d2", "meteofrance_arome_france_hd", "icon_global"],
      hourly: [],
      referenceId: "icon_d2",
      headlineC: 25.4,
      headlineKind: "blend",
      consensusCorrectedC: 25.4,
      consensusRawC: 25.2,
      consensusModelIds: ["icon_d2", "meteofrance_arome_france_hd"],
      spreadC: { min: 24.9, max: 25.9 },
      peak: null,
      fetchedAt: "2026-09-16T09:00:00.000Z",
      stale: false,
      ensemble: {
        ok: true,
        lead: "J0_10h30",
        recipeDate: "2026-09-16",
        generatedUtc: "2026-09-16T06:00:00Z",
        correctionMethod: "expanding",
        blendMethod: "mean · all",
        blendC: 25.4,
        blendRawC: 25.2,
        spreadC: 0.5,
        mu: 25.6,
        sd: 1.0,
        probs: [
          { k: 24, p: 0.15 },
          { k: 25, p: 0.3 },
          { k: 26, p: 0.41 },
          { k: 27, p: 0.14 },
        ],
        kTop: 26,
        pTop: 0.41,
        range80: { lo: 25, hi: 27 },
        truncatedAt: 24,
        selected: ["icon_d2", "meteofrance_arome_france_hd"],
      },
    },
    metar: {
      ok: true,
      fetchedAt: "2026-09-16T09:00:00.000Z",
      stale: false,
      runningMaxC: 25.0,
      runningMaxAt: "2026-09-16T12:53:00.000Z",
      resolutionMaxC: 24,
      latest: {
        tempC: 23.3,
        tempBodyC: 23,
        dewpointC: 10,
        observedAt: "2026-09-16T12:53:00.000Z",
        raw: "EDDM 161253Z 00000KT CAVOK 23/10 Q1015",
        icon: "clear",
      },
    },
    wu: {
      ok: true,
      stationId: "EDDM",
      dailyMaxC: 26,
      predictedHighC: 26,
      lowC: 12.0,
      currentTempC: 23.3,
      fetchedAt: "2026-09-16T09:00:00.000Z",
      stale: false,
      forecastUrl: "https://www.wunderground.com/forecast/EDDM",
    },
    husky: {
      ok: true,
      dailyMaxC: 25,
      localDate: "2026-09-16",
      fetchedAt: "2026-09-16T09:00:00.000Z",
      stale: false,
      url: "https://huskyweather.com/station/EDDM",
    },
    polymarket: {
      ok: true,
      slug: "highest-temperature-in-munich-on-september-16-2026",
      unit: "C",
      step: 1,
      buckets: [],
      fetchedAt: "2026-09-16T09:00:00.000Z",
      stale: false,
    },
    synoptic: {
      ok: false,
      configured: false,
      resolutionMax: null,
      resolutionMaxAt: null,
      maxC: null,
      latestC: null,
      latestAt: null,
      observationCount: 0,
      unit: "C",
      fetchedAt: "2026-09-16T09:00:00.000Z",
      stale: false,
    },
    pws: { stations: [], fetchedAt: "2026-09-16T09:00:00.000Z", stale: false },
    drivers: {
      modelId: "icon_d2",
      windowLabel: "",
      aroundPeak: {
        avgCloudCover: null,
        maxPrecipProb: null,
        sumPrecipMm: null,
        avgWindSpeedMps: null,
        maxGustMps: null,
        avgShortwaveWm2: null,
        dominantWeatherCode: null,
      },
      now: {
        cloudCover: null,
        precipProb: null,
        precipMm: null,
        windSpeedMps: null,
        shortwaveWm2: null,
        humidityPct: null,
        metarWindKt: null,
        metarWindDirDeg: null,
        metarGustKt: null,
      },
      flags: [],
    },
    compareAll: false,
    ...overrides,
  };
}
